package auca.ac.rw.diabetesmonitoring.service;

import auca.ac.rw.diabetesmonitoring.dto.SystemSettingsDto;
import auca.ac.rw.diabetesmonitoring.model.SystemSettings;
import auca.ac.rw.diabetesmonitoring.model.User;
import auca.ac.rw.diabetesmonitoring.repository.SystemSettingsRepository;
import auca.ac.rw.diabetesmonitoring.repository.UserRepository;
import org.springframework.stereotype.Service;

@Service
public class SystemSettingsService {

    private static final Long SETTINGS_ID = 1L;

    private final SystemSettingsRepository systemSettingsRepository;
    private final UserRepository userRepository;
    private final AuditLogService auditLogService;

    public SystemSettingsService(SystemSettingsRepository systemSettingsRepository, UserRepository userRepository,
                                  AuditLogService auditLogService) {
        this.systemSettingsRepository = systemSettingsRepository;
        this.userRepository = userRepository;
        this.auditLogService = auditLogService;
    }

    public SystemSettingsDto getBranding() {
        return SystemSettingsDto.from(currentOrDefault());
    }

    public SystemSettingsDto updateBranding(SystemSettingsDto request, String principalName) {
        SystemSettings settings = currentOrDefault();
        settings.setSystemName(request.getSystemName());
        settings.setLogoUrl(request.getLogoUrl());
        settings.setWatermarkUrl(request.getWatermarkUrl());
        settings.setWatermarkText(request.getWatermarkText());
        settings.setFooter(request.getFooter());
        settings.setConfidentialityNotice(request.getConfidentialityNotice());
        SystemSettings saved = systemSettingsRepository.save(settings);

        User actor = userRepository.findByUsername(principalName).or(() -> userRepository.findByEmail(principalName)).orElse(null);
        auditLogService.log("SETTINGS_UPDATED", "SUCCESS", actor == null ? principalName : actor.getEmail(),
                actor == null ? null : actor.getRole(), "Report branding settings updated");
        return SystemSettingsDto.from(saved);
    }

    private SystemSettings currentOrDefault() {
        return systemSettingsRepository.findById(SETTINGS_ID).orElseGet(() -> {
            SystemSettings defaults = new SystemSettings();
            defaults.setSystemName("Diacare Diabetes Monitoring");
            defaults.setLogoUrl("");
            defaults.setWatermarkUrl("");
            defaults.setWatermarkText("DIACARE");
            defaults.setFooter("Generated by Diacare — confidential patient information.");
            defaults.setConfidentialityNotice("This report contains confidential patient health information. "
                    + "It is intended only for the individual or entity to which it is addressed and may contain information "
                    + "that is privileged, confidential, and exempt from disclosure. Unauthorized use, disclosure, or copying "
                    + "is strictly prohibited.");
            return defaults;
        });
    }
}
