import { useEffect, useState } from 'react';
import Card from '../../../components/common/Card.jsx';
import ExportButtons from '../../../components/common/ExportButtons.jsx';
import LoadingSpinner from '../../../components/common/LoadingSpinner.jsx';
import Pagination from '../../../components/common/Pagination.jsx';
import StatusBadge from '../../../components/common/StatusBadge.jsx';
import Table, { RowActions } from '../../../components/common/Table.jsx';
import useToast from '../../../hooks/useToast.js';
import { downloadReportFile, filterReportHistory } from '../../../services/reportService.js';
import { formatDate, formatDateTime } from '../../../utils/reportFormatting.js';
import ReportDownloadActions from './ReportDownloadActions.jsx';
import ReportFilters from './ReportFilters.jsx';

function ReportHistoryPage() {
  const [filters, setFilters] = useState({});
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(10);
  const { showToast } = useToast();

  async function loadHistory() {
    setLoading(true);
    try {
      setHistory(await filterReportHistory(filters));
      setPage(0);
    } catch {
      showToast({ type: 'error', message: 'Unable to load report history.' });
    } finally {
      setLoading(false);
    }
  }

  async function handleDownload(reportId, format) {
    try {
      await downloadReportFile(reportId, format);
      showToast({ type: 'success', message: `${format} download started.` });
    } catch {
      showToast({ type: 'error', message: 'Unable to download this report.' });
    }
  }

  useEffect(() => {
    loadHistory();
  }, []);

  const totalPages = Math.ceil(history.length / pageSize);
  const visibleHistory = history.slice(page * pageSize, page * pageSize + pageSize);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-[#334155]">Report History</h1>
        <p className="mt-2 text-sm text-[#334155]/80">Visible history follows the permissions of the logged-in role.</p>
      </div>

      <ReportFilters
        filters={filters}
        setFilters={setFilters}
        onApply={loadHistory}
        onReset={() => setFilters({})}
        showPatient
        showDoctor
        showRole
      />

      <ExportButtons data={history} fileName="report-history" />

      <Card>
        {loading ? (
          <LoadingSpinner label="Loading report history..." />
        ) : (
          <Table
            columns={[
              { key: 'reportName', header: 'Report name' },
              { key: 'reportType', header: 'Type' },
              { key: 'generatedBy', header: 'Generated by' },
              { key: 'generatedFor', header: 'Generated for' },
              { key: 'generatedDate', header: 'Generated date', render: (row) => formatDateTime(row.generatedDate) },
              { key: 'downloadedDate', header: 'Downloaded date', render: (row) => formatDateTime(row.downloadedDate) },
              { key: 'fileFormat', header: 'Format' },
              {
                key: 'downloadStatus',
                header: 'Status',
                render: (row) => <StatusBadge status={row.downloadStatus || 'PENDING'} />
              },
              {
                key: 'dateRange',
                header: 'Date range',
                render: (row) => `${formatDate(row.dateFrom || row.startDate)} to ${formatDate(row.dateTo || row.endDate)}`
              },
              {
                key: 'actions',
                header: '',
                sortable: false,
                render: (row) => (
                  <RowActions actions={[
                    { label: 'Download PDF', onClick: () => handleDownload(row.id, 'PDF'), disabled: !row.id },
                    { label: 'Download CSV', onClick: () => handleDownload(row.id, 'CSV'), disabled: !row.id },
                    { label: 'Download Excel', onClick: () => handleDownload(row.id, 'EXCEL'), disabled: !row.id },
                  ]} />
                )
              }
            ]}
            data={visibleHistory}
            emptyMessage="No data available for this section."
          />
        )}
      </Card>
      {!loading && (
        <Pagination
          page={page}
          totalPages={totalPages}
          totalItems={history.length}
          pageSize={pageSize}
          onPageChange={setPage}
          onPageSizeChange={(size) => {
            setPageSize(size);
            setPage(0);
          }}
        />
      )}
    </div>
  );
}

export default ReportHistoryPage;
