import { useEffect, useState } from 'react';
import { MdBusiness, MdDescription, MdPrint, MdSave } from 'react-icons/md';
import Button from '../../../components/common/Button.jsx';
import Card from '../../../components/common/Card.jsx';
import Input from '../../../components/common/Input.jsx';
import LoadingSpinner from '../../../components/common/LoadingSpinner.jsx';
import useToast from '../../../hooks/useToast.js';
import { getReportBranding, updateReportBranding } from '../../../services/systemSettingsService.js';

const defaultBranding = {
  systemName: '',
  logoUrl: '',
  watermarkUrl: '',
  watermarkText: '',
  footer: '',
  confidentialityNotice: ''
};

function SectionHeading({ icon: Icon, title, description }) {
  return (
    <div className="mb-4 flex items-center gap-2.5">
      <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#2563EB]/10">
        <Icon size={16} className="text-[#2563EB]" />
      </div>
      <div>
        <h2 className="text-sm font-semibold text-[#1e293b]">{title}</h2>
        {description && <p className="text-xs text-[#94a3b8]">{description}</p>}
      </div>
    </div>
  );
}

function TextArea({ label, id, value, onChange, rows = 3, maxLength }) {
  return (
    <div className="space-y-2">
      <label htmlFor={id} className="block text-sm font-semibold text-[#334155]">
        {label}
      </label>
      <textarea
        id={id}
        rows={rows}
        maxLength={maxLength}
        value={value}
        onChange={onChange}
        className="w-full rounded-md border border-[#334155]/25 bg-[#FFFFFF] px-3 py-2 text-base text-[#334155] outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-[#2563EB]/20"
      />
      {maxLength && <p className="text-xs font-medium text-[#334155]/60">{value.length}/{maxLength} characters</p>}
    </div>
  );
}

function BrandingPreview({ branding }) {
  return (
    <div className="relative overflow-hidden rounded-xl border border-[#E2E8F0] bg-white p-6">
      {branding.watermarkUrl && (
        <img
          src={branding.watermarkUrl}
          alt=""
          className="pointer-events-none absolute inset-0 m-auto h-48 w-48 object-contain opacity-10"
          onError={(event) => {
            event.currentTarget.style.display = 'none';
          }}
        />
      )}
      {branding.watermarkText && (
        <p className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-center text-4xl font-bold uppercase text-[#334155]/10">
          {branding.watermarkText}
        </p>
      )}

      <div className="relative space-y-6">
        <div className="flex items-center justify-between gap-4 border-b border-[#F1F5F9] pb-4">
          <div className="flex items-center gap-3">
            <div className="flex h-14 w-14 items-center justify-center rounded-lg border border-[#E2E8F0] bg-white">
              {branding.logoUrl ? (
                <img
                  src={branding.logoUrl}
                  alt="System logo preview"
                  className="max-h-12 max-w-12 object-contain"
                  onError={(event) => {
                    event.currentTarget.style.display = 'none';
                  }}
                />
              ) : (
                <span className="text-sm font-bold text-[#2563EB]">Logo</span>
              )}
            </div>
            <div>
              <p className="text-xs font-semibold uppercase tracking-wide text-[#2563EB]">Report Preview</p>
              <h2 className="text-xl font-bold text-[#334155]">{branding.systemName || 'System Name'}</h2>
            </div>
          </div>
          <div className="text-right text-xs font-semibold text-[#94a3b8]">
            <p>Date Generated</p>
            <p>{new Date().toLocaleDateString()}</p>
          </div>
        </div>

        <div className="grid gap-3 md:grid-cols-3">
          <div className="rounded-lg bg-[#F8FAFC] p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#94a3b8]">Report Title</p>
            <p className="mt-1 text-sm font-bold text-[#334155]">Clinical Summary</p>
          </div>
          <div className="rounded-lg bg-[#F8FAFC] p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#94a3b8]">Generated By</p>
            <p className="mt-1 text-sm font-bold text-[#334155]">Admin User</p>
          </div>
          <div className="rounded-lg bg-[#F8FAFC] p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-[#94a3b8]">Selected Date Range</p>
            <p className="mt-1 text-sm font-bold text-[#334155]">Current month</p>
          </div>
        </div>

        <div className="rounded-lg border border-[#F1F5F9] p-4">
          <h3 className="text-sm font-bold text-[#334155]">Confidentiality Notice</h3>
          <p className="mt-2 text-sm leading-6 text-[#334155]/80">
            {branding.confidentialityNotice || 'Confidentiality notice will appear here.'}
          </p>
        </div>

        <div className="border-t border-[#F1F5F9] pt-4 text-center text-sm font-semibold text-[#334155]/70">
          {branding.footer || 'Footer text will appear here.'}
        </div>
      </div>
    </div>
  );
}

function SystemSettingsPage() {
  const [branding, setBranding] = useState(defaultBranding);
  const [updatedAt, setUpdatedAt] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const { showToast } = useToast();

  const updateField = (field, value) => {
    setBranding((current) => ({ ...current, [field]: value }));
  };

  useEffect(() => {
    async function loadBranding() {
      try {
        const data = await getReportBranding();
        setBranding({ ...defaultBranding, ...data });
        setUpdatedAt(data?.updatedAt || null);
      } catch {
        showToast({ type: 'error', message: 'Unable to load report branding settings.' });
      } finally {
        setLoading(false);
      }
    }

    loadBranding();
  }, [showToast]);

  async function saveSettings(event) {
    event.preventDefault();

    const requiredFields = ['systemName', 'logoUrl', 'watermarkUrl', 'watermarkText'];
    const hasMissingField = requiredFields.some((field) => !branding[field]?.trim());

    if (hasMissingField) {
      showToast({ type: 'warning', message: 'Please fill in the required fields.' });
      return;
    }

    setSaving(true);
    try {
      const saved = await updateReportBranding({
        systemName: branding.systemName.trim(),
        logoUrl: branding.logoUrl.trim(),
        watermarkUrl: branding.watermarkUrl.trim(),
        watermarkText: branding.watermarkText.trim(),
        footer: branding.footer.trim(),
        confidentialityNotice: branding.confidentialityNotice.trim()
      });
      setBranding({ ...defaultBranding, ...saved });
      setUpdatedAt(saved?.updatedAt || null);
      showToast({ type: 'success', message: 'Report branding settings saved.' });
    } catch {
      showToast({ type: 'error', message: 'Unable to save report branding settings.' });
    } finally {
      setSaving(false);
    }
  }

  if (loading) {
    return <LoadingSpinner label="Loading system settings..." />;
  }

  return (
    <div className="space-y-6">
      <div className="border-b border-[#E2E8F0] pb-5">
        <p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#2563EB]">Admin</p>
        <h1 className="mt-1 text-2xl font-bold text-[#1e293b]">System Settings</h1>
        <p className="mt-1 max-w-3xl text-sm text-[#64748b]">
          Update the branding used on generated reports. Previously generated reports keep the branding that was active when they were created.
        </p>
        {updatedAt && <p className="mt-1 text-xs text-[#94a3b8]">Last updated {new Date(updatedAt).toLocaleString()}</p>}
      </div>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,0.9fr)]">
        <form className="space-y-4" onSubmit={saveSettings}>
          <Card>
            <SectionHeading icon={MdBusiness} title="Organization Identity" description="Shown at the top of every generated report." />
            <div className="space-y-4">
              <Input
                label="System name"
                id="systemName"
                maxLength={200}
                value={branding.systemName}
                onChange={(event) => updateField('systemName', event.target.value)}
                required
              />
              <Input
                label="Logo URL"
                id="logoUrl"
                maxLength={1000}
                value={branding.logoUrl}
                onChange={(event) => updateField('logoUrl', event.target.value)}
                required
              />
            </div>
          </Card>

          <Card>
            <SectionHeading icon={MdDescription} title="Report Document" description="Watermark, footer, and confidentiality notice for report exports." />
            <div className="space-y-4">
              <Input
                label="Watermark URL"
                id="watermarkUrl"
                maxLength={1000}
                value={branding.watermarkUrl}
                onChange={(event) => updateField('watermarkUrl', event.target.value)}
                required
              />
              <Input
                label="Watermark text"
                id="watermarkText"
                maxLength={300}
                value={branding.watermarkText}
                onChange={(event) => updateField('watermarkText', event.target.value)}
                required
              />
              <TextArea
                label="Footer text"
                id="footer"
                maxLength={500}
                value={branding.footer}
                onChange={(event) => updateField('footer', event.target.value)}
              />
              <TextArea
                label="Confidentiality notice"
                id="confidentialityNotice"
                rows={5}
                maxLength={1000}
                value={branding.confidentialityNotice}
                onChange={(event) => updateField('confidentialityNotice', event.target.value)}
              />
            </div>
          </Card>

          <div className="flex flex-wrap gap-3">
            <Button type="submit" disabled={saving} className="flex items-center gap-1.5">
              <MdSave size={16} /> {saving ? 'Saving...' : 'Save settings'}
            </Button>
            <Button type="button" variant="secondary" className="flex items-center gap-1.5" onClick={() => window.print()}>
              <MdPrint size={16} /> Print preview
            </Button>
          </div>
        </form>

        <div className="space-y-3">
          <h2 className="text-sm font-semibold text-[#1e293b]">Report Branding Preview</h2>
          <BrandingPreview branding={branding} />
        </div>
      </div>
    </div>
  );
}

export default SystemSettingsPage;
