import Button from '../../../components/common/Button.jsx';
import Card from '../../../components/common/Card.jsx';
import Input from '../../../components/common/Input.jsx';
import StaffSelect from '../../../components/common/StaffSelect.jsx';

const diabetesTypes = ['TYPE_1', 'TYPE_2', 'GESTATIONAL', 'PREDIABETES', 'OTHER'];
const statuses = ['ACTIVE', 'INACTIVE'];
const genders = ['', 'FEMALE', 'MALE', 'OTHER'];

function PatientForm({ title, description, formData, onChange, onSubmit, submitting, submitLabel, error }) {
  return (
    <Card className="mx-auto max-w-5xl">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-[#334155]">{title}</h1>
        {description && <p className="mt-2 text-sm text-[#334155]/80">{description}</p>}
      </div>

      <form className="space-y-5" onSubmit={onSubmit}>
        <div className="grid gap-4 md:grid-cols-2">
          <Input id="firstName" name="firstName" label="First name" value={formData.firstName} onChange={onChange} minLength={2} required />
          <Input id="lastName" name="lastName" label="Last name" value={formData.lastName} onChange={onChange} minLength={2} required />
          <Input id="patientId" name="patientId" label="Patient ID" value={formData.patientId || ''} onChange={onChange} disabled placeholder="Generated by system" />
          <Input id="email" name="email" label="Email" type="email" value={formData.email} onChange={onChange} required />
          <Input id="phone" name="phone" label="Phone number" type="tel" value={formData.phone} onChange={onChange} />
          <Input id="dateOfBirth" name="dateOfBirth" label="Date of birth" type="date" value={formData.dateOfBirth} onChange={onChange} required />
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <SelectField label="Gender" name="gender" value={formData.gender} onChange={onChange} options={genders} />
          <SelectField label="Diabetes type" name="diabetesType" value={formData.diabetesType} onChange={onChange} options={diabetesTypes} />
          <Input id="diagnosisDate" name="diagnosisDate" label="Diagnosis date" type="date" value={formData.diagnosisDate} onChange={onChange} />
          <SelectField label="Status" name="status" value={formData.status} onChange={onChange} options={statuses} />
          <Input id="address" name="address" label="Address" value={formData.address} onChange={onChange} />
          <Input id="emergencyContactName" name="emergencyContactName" label="Emergency contact name" value={formData.emergencyContactName} onChange={onChange} />
          <Input id="emergencyContactPhone" name="emergencyContactPhone" label="Emergency contact phone" value={formData.emergencyContactPhone} onChange={onChange} />
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          <StaffSelect name="doctorId" label="Doctor" role="DOCTOR" value={formData.doctorId} onChange={onChange} />
          <StaffSelect name="nurseId" label="Nurse" role="NURSE" value={formData.nurseId} onChange={onChange} />
          <StaffSelect name="caregiverId" label="Caregiver" role="CAREGIVER" value={formData.caregiverId} onChange={onChange} />
        </div>

        {error && <p className="rounded-md border border-[#DC2626]/25 bg-[#DC2626]/10 px-3 py-2 text-sm text-[#DC2626]">{error}</p>}

        <div className="flex justify-end">
          <Button type="submit" disabled={submitting}>
            {submitting ? 'Saving...' : submitLabel}
          </Button>
        </div>
      </form>
    </Card>
  );
}

function SelectField({ label, name, value, onChange, options }) {
  return (
    <div className="space-y-2">
      <label htmlFor={name} className="block text-sm font-semibold text-[#334155]">
        {label}
      </label>
      <select
        id={name}
        name={name}
        value={value}
        onChange={onChange}
        className="min-h-11 w-full rounded-md border border-[#334155]/25 bg-[#FFFFFF] px-3 text-base text-[#334155] outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-[#2563EB]/20"
      >
        {options.map((option) => (
          <option key={option} value={option}>
            {option || 'Not specified'}
          </option>
        ))}
      </select>
    </div>
  );
}

export default PatientForm;
