import NotificationModulePage from './NotificationModulePage.jsx';

function MedicationReminders() {
  return (
    <NotificationModulePage
      title="Medication Reminders"
      eyebrow="Medication"
      description="View medication reminder notifications generated by the backend. This page does not recommend or change medication dosage."
      fixedCategory="MEDICATION_REMINDER"
      banner={{
        title: 'Medication safety',
        message: 'Medication reminders are for scheduling support only. Do not change medication or dosage without advice from a qualified healthcare professional.',
        variant: 'info',
        badge: 'SAFETY'
      }}
    />
  );
}

export default MedicationReminders;
